{% set version = "4.18.1" %}

package:
  name: selenium-manager
  version: {{ version }}

source:
  url: https://github.com/SeleniumHQ/selenium/archive/refs/tags/selenium-{{ version }}.tar.gz
  sha256: 6e5c8903253f9541bc839e3e31f99680d8ceb202b2b6d75ebe51e95f348ee1c5

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - selenium-manager --version
    - selenium-manager --help
    - '"${SE_MANAGER_PATH}" --version'  # [not win]
    - '%SE_MANAGER_PATH% --version'  # [win]

about:
  home: https://github.com/SeleniumHQ/selenium
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE
    - NOTICE
  summary: |-
    Selenium Manager is a standalone tool that automatically manages the browser
    infrastructure required by Selenium (i.e., browsers and drivers).

extra:
  recipe-maintainers:
    - conda-forge/selenium
    - bollwyvl
