{% set version = "4.14.0" %}

package:
  name: selenium-manager
  version: {{ version }}

source:
  url: https://github.com/SeleniumHQ/selenium/archive/refs/tags/selenium-{{ version }}.tar.gz
  sha256: d995a7120362c540a176180642da05165d5c5fc97409effd3a51ec0f0bfe3153

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - selenium-manager --version
    - selenium-manager --help
    - '"${SE_MANAGER_PATH}" --version'  # [not win]
    - '%SE_MANAGER_PATH% --version'  # [win]

about:
  home: https://github.com/SeleniumHQ/selenium
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE
    - NOTICE
  summary: |-
    Selenium Manager is a standalone tool that automatically manages the browser
    infrastructure required by Selenium (i.e., browsers and drivers).

extra:
  recipe-maintainers:
    - conda-forge/selenium
    - bollwyvl
